import 'package:flutter/material.dart';

import 'models.dart';
import 'senpwai_theme.dart';

enum SenpwaiThemePreset {
  defaultTheme,
  gruvbox,
  catppuccin,
  monokai;

  String get label => switch (this) {
    SenpwaiThemePreset.defaultTheme => 'Default',
    SenpwaiThemePreset.gruvbox => 'Gruvbox',
    SenpwaiThemePreset.catppuccin => 'Catppuccin',
    SenpwaiThemePreset.monokai => 'Monokai',
  };

  Color get swatch => toTheme().colors.dark.primary;

  SenpwaiTheme toTheme() => switch (this) {
    SenpwaiThemePreset.defaultTheme => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFC4384E),
          secondary: Color(0xFFFF6B8A),
          tertiary: Color(0xFF4DD4E6),
          background: Color(0xFF080A0F),
          surface: Color(0xFF11141C),
          surfaceVariant: Color(0xFF1C1F2A),
          onSurface: Color(0xFFE2E8F0),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFFF3333),
          imageOverlay: Color(0xFF000000),
          onImageOverlay: Color(0xFFFFFFFF),
          textShadow: Color(0x8A000000),
          genreColors: [
            Color(0xFFEF5350),
            Color(0xFFEC407A),
            Color(0xFFAB47BC),
            Color(0xFF7E57C2),
            Color(0xFF42A5F5),
            Color(0xFF26C6DA),
            Color(0xFF26A69A),
            Color(0xFF66BB6A),
            Color(0xFFD4E157),
            Color(0xFFFFCA28),
            Color(0xFFFFA726),
            Color(0xFF8D6E63),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF9B2C3E),
          secondary: Color(0xFFD14D6A),
          tertiary: Color(0xFF1A8FA0),
          background: Color(0xFFF5F0F1),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFF0E6E8),
          onSurface: Color(0xFF1A1A2E),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFCC2222),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF1A1A2E),
          textShadow: Color(0x8AFFFFFF),
          genreColors: [
            Color(0xFFEF5350),
            Color(0xFFEC407A),
            Color(0xFFAB47BC),
            Color(0xFF7E57C2),
            Color(0xFF42A5F5),
            Color(0xFF26C6DA),
            Color(0xFF26A69A),
            Color(0xFF66BB6A),
            Color(0xFFD4E157),
            Color(0xFFFFCA28),
            Color(0xFFFFA726),
            Color(0xFF8D6E63),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Orbitron',
        bodyFamily: 'Exo 2',
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 4,
        cardBorderWidth: 1,
        inputRadius: 4,
        buttonRadius: 4,
      ),
    ),
    SenpwaiThemePreset.gruvbox => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFD79921),
          secondary: Color(0xFFB8BB26),
          tertiary: Color(0xFF83A598),
          background: Color(0xFF1D2021),
          surface: Color(0xFF282828),
          surfaceVariant: Color(0xFF3C3836),
          onSurface: Color(0xFFEBDBB2),
          onPrimary: Color(0xFF1D2021),
          error: Color(0xFFCC241D),
          imageOverlay: Color(0xFF1D2021),
          onImageOverlay: Color(0xFFEBDBB2),
          textShadow: Color(0x8A000000),
          genreColors: [
            Color(0xFFFF6D00),
            Color(0xFFD79921),
            Color(0xFF8EC07C),
            Color(0xFF83A598),
            Color(0xFFB57614),
            Color(0xFFCC241D),
            Color(0xFFD65D0E),
            Color(0xFF458588),
            Color(0xFF689D6A),
            Color(0xFFB8BB26),
            Color(0xFFD3869B),
            Color(0xFF98971A),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFFB57614),
          secondary: Color(0xFF79740E),
          tertiary: Color(0xFF427B58),
          background: Color(0xFFFBF1C7),
          surface: Color(0xFFF2E5BC),
          surfaceVariant: Color(0xFFEBDBB2),
          onSurface: Color(0xFF3C3836),
          onPrimary: Color(0xFFFBF1C7),
          error: Color(0xFF9D0006),
          imageOverlay: Color(0xFFFBF1C7),
          onImageOverlay: Color(0xFF3C3836),
          textShadow: Color(0x8AFFFFFF),
          genreColors: [
            Color(0xFFFF6D00),
            Color(0xFFD79921),
            Color(0xFF8EC07C),
            Color(0xFF83A598),
            Color(0xFFB57614),
            Color(0xFFCC241D),
            Color(0xFFD65D0E),
            Color(0xFF458588),
            Color(0xFF689D6A),
            Color(0xFFB8BB26),
            Color(0xFFD3869B),
            Color(0xFF98971A),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Bitter',
        bodyFamily: 'Source Sans 3',
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 6,
        cardBorderWidth: 1.5,
        inputRadius: 6,
        buttonRadius: 6,
      ),
    ),
    SenpwaiThemePreset.catppuccin => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFCBA6F7),
          secondary: Color(0xFFF5C2E7),
          tertiary: Color(0xFF94E2D5),
          background: Color(0xFF1E1E2E),
          surface: Color(0xFF181825),
          surfaceVariant: Color(0xFF313244),
          onSurface: Color(0xFFCDD6F4),
          onPrimary: Color(0xFF1E1E2E),
          error: Color(0xFFF38BA8),
          imageOverlay: Color(0xFF1E1E2E),
          onImageOverlay: Color(0xFFCDD6F4),
          textShadow: Color(0x8A000000),
          genreColors: [
            Color(0xFFEBA0AC),
            Color(0xFFF5C2E7),
            Color(0xFFCBA6F7),
            Color(0xFF89B4FA),
            Color(0xFF74C7EC),
            Color(0xFF89DCEB),
            Color(0xFF94E2D5),
            Color(0xFFA6E3A1),
            Color(0xFFB5E8B0),
            Color(0xFFFFD080),
            Color(0xFFFAB387),
            Color(0xFFF38BA8),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF8839EF),
          secondary: Color(0xFFEA76CB),
          tertiary: Color(0xFF179299),
          background: Color(0xFFEFF1F5),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFE6E9EF),
          onSurface: Color(0xFF4C4F69),
          onPrimary: Color(0xFFEFF1F5),
          error: Color(0xFFD20F39),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF4C4F69),
          textShadow: Color(0x8AFFFFFF),
          genreColors: [
            Color(0xFFEBA0AC),
            Color(0xFFF5C2E7),
            Color(0xFFCBA6F7),
            Color(0xFF89B4FA),
            Color(0xFF74C7EC),
            Color(0xFF89DCEB),
            Color(0xFF94E2D5),
            Color(0xFFA6E3A1),
            Color(0xFFB5E8B0),
            Color(0xFFFFD080),
            Color(0xFFFAB387),
            Color(0xFFF38BA8),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Comfortaa',
        bodyFamily: 'Nunito Sans',
        displayWeight: FontWeight.w600,
        headlineWeight: FontWeight.w500,
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 10,
        cardBorderWidth: 0,
        inputRadius: 10,
        buttonRadius: 10,
      ),
    ),
    SenpwaiThemePreset.monokai => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFA6E22E),
          secondary: Color(0xFFF92672),
          tertiary: Color(0xFF66D9EF),
          background: Color(0xFF1E1F1C),
          surface: Color(0xFF272822),
          surfaceVariant: Color(0xFF3E3D32),
          onSurface: Color(0xFFF8F8F2),
          onPrimary: Color(0xFF272822),
          error: Color(0xFFF92672),
          imageOverlay: Color(0xFF1E1F1C),
          onImageOverlay: Color(0xFFF8F8F2),
          textShadow: Color(0x8A000000),
          genreColors: [
            Color(0xFFA6E22E),
            Color(0xFFF92672),
            Color(0xFF66D9EF),
            Color(0xFFE6DB74),
            Color(0xFFFD971F),
            Color(0xFF819AFF),
            Color(0xFFCC66FF),
            Color(0xFF4DD4E6),
            Color(0xFFFF7043),
            Color(0xFF80CBC4),
            Color(0xFFFF80AB),
            Color(0xFFB9EE6A),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF4D7A0F),
          secondary: Color(0xFFC2185B),
          tertiary: Color(0xFF0277BD),
          background: Color(0xFFF8F8F2),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFEEEDE5),
          onSurface: Color(0xFF272822),
          onPrimary: Color(0xFFF8F8F2),
          error: Color(0xFFC2185B),
          imageOverlay: Color(0xFFF8F8F2),
          onImageOverlay: Color(0xFF272822),
          textShadow: Color(0x8AFFFFFF),
          genreColors: [
            Color(0xFFA6E22E),
            Color(0xFFF92672),
            Color(0xFF66D9EF),
            Color(0xFFE6DB74),
            Color(0xFFFD971F),
            Color(0xFF819AFF),
            Color(0xFFCC66FF),
            Color(0xFF4DD4E6),
            Color(0xFFFF7043),
            Color(0xFF80CBC4),
            Color(0xFFFF80AB),
            Color(0xFFB9EE6A),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'JetBrains Mono',
        bodyFamily: 'Barlow',
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 2,
        cardBorderWidth: 1,
        inputRadius: 2,
        buttonRadius: 2,
      ),
    ),
  };
}
