import 'package:flutter/material.dart';

import 'models.dart';
import 'senpwai_theme.dart';

enum SenpwaiThemePreset {
  defaultTheme,
  naruto,
  kaneki,
  gojo,
  deku;

  String get label => switch (this) {
    SenpwaiThemePreset.defaultTheme => 'Default',
    SenpwaiThemePreset.naruto => 'Naruto',
    SenpwaiThemePreset.kaneki => 'Kaneki',
    SenpwaiThemePreset.gojo => 'Gojo',
    SenpwaiThemePreset.deku => 'Deku',
  };

  Color get swatch => toTheme().colors.dark.primary;

  SenpwaiTheme toTheme() => switch (this) {
    // ── Default ──────────────────────────────────────────────────────
    SenpwaiThemePreset.defaultTheme => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFC4384E),
          secondary: Color(0xFFFF6B8A),
          tertiary: Color(0xFF4DD4E6),
          background: Color(0xFF080A0F),
          surface: Color(0xFF11141C),
          surfaceVariant: Color(0xFF1C1F2A),
          onSurface: Color(0xFFE2E8F0),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFFF3333),
          imageOverlay: Color(0xFF000000),
          onImageOverlay: Color(0xFFFFFFFF),
          textShadow: Color(0x8A000000),
          randomColors: [
            Color(0xFFEF5350),
            Color(0xFFEC407A),
            Color(0xFFAB47BC),
            Color(0xFF7E57C2),
            Color(0xFF42A5F5),
            Color(0xFF26C6DA),
            Color(0xFF26A69A),
            Color(0xFF66BB6A),
            Color(0xFFD4E157),
            Color(0xFFFFCA28),
            Color(0xFFFFA726),
            Color(0xFF8D6E63),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF9B2C3E),
          secondary: Color(0xFFD14D6A),
          tertiary: Color(0xFF1A8FA0),
          background: Color(0xFFF5F0F1),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFF0E6E8),
          onSurface: Color(0xFF1A1A2E),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFCC2222),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF1A1A2E),
          textShadow: Color(0x8AFFFFFF),
          randomColors: [
            Color(0xFFEF5350),
            Color(0xFFEC407A),
            Color(0xFFAB47BC),
            Color(0xFF7E57C2),
            Color(0xFF42A5F5),
            Color(0xFF26C6DA),
            Color(0xFF26A69A),
            Color(0xFF66BB6A),
            Color(0xFFD4E157),
            Color(0xFFFFCA28),
            Color(0xFFFFA726),
            Color(0xFF8D6E63),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Orbitron',
        bodyFamily: 'Exo 2',
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 4,
        cardBorderWidth: 1,
        inputRadius: 4,
        buttonRadius: 4,
      ),
    ),

    // ── Naruto ───────────────────────────────────────────────────────
    // Orange on black/white, warm & welcoming, rounded
    SenpwaiThemePreset.naruto => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFFF7B00),
          secondary: Color(0xFFE65100),
          tertiary: Color(0xFF38BDF8),
          background: Color(0xFF0A0A0A),
          surface: Color(0xFF141414),
          surfaceVariant: Color(0xFF1F1F1F),
          onSurface: Color(0xFFF5F5F5),
          onPrimary: Color(0xFF000000),
          error: Color(0xFFEF4444),
          imageOverlay: Color(0xFF000000),
          onImageOverlay: Color(0xFFF5F5F5),
          textShadow: Color(0x8A000000),
          randomColors: [
            Color(0xFFFF8C00),
            Color(0xFFFF6D00),
            Color(0xFFFFA726),
            Color(0xFFEF5350),
            Color(0xFF38BDF8),
            Color(0xFF26A69A),
            Color(0xFFFFD54F),
            Color(0xFFD84315),
            Color(0xFFFF7043),
            Color(0xFF8BC34A),
            Color(0xFF8D6E63),
            Color(0xFFFBC02D),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFFE86800),
          secondary: Color(0xFFC55A11),
          tertiary: Color(0xFF1D7A9C),
          background: Color(0xFFFFF8F0),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFFFF0E0),
          onSurface: Color(0xFF1A1A1A),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFDC2626),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF1A1A1A),
          textShadow: Color(0x8AFFFFFF),
          randomColors: [
            Color(0xFFFF8C00),
            Color(0xFFFF6D00),
            Color(0xFFFFA726),
            Color(0xFFEF5350),
            Color(0xFF38BDF8),
            Color(0xFF26A69A),
            Color(0xFFFFD54F),
            Color(0xFFD84315),
            Color(0xFFFF7043),
            Color(0xFF8BC34A),
            Color(0xFF8D6E63),
            Color(0xFFFBC02D),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Baloo 2',
        bodyFamily: 'Nunito Sans',
        displayWeight: FontWeight.w700,
        headlineWeight: FontWeight.w600,
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 12,
        cardBorderWidth: 1,
        inputRadius: 12,
        buttonRadius: 12,
      ),
    ),

    // ── Kaneki ───────────────────────────────────────────────────────
    // Strong blacks & whites, scarce blood reds, hard edges, gothic
    SenpwaiThemePreset.kaneki => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFFE0E0E0),
          secondary: Color(0xFF8B0000),
          tertiary: Color(0xFF808080),
          background: Color(0xFF050505),
          surface: Color(0xFF0A0A0A),
          surfaceVariant: Color(0xFF151515),
          onSurface: Color(0xFFD0D0D0),
          onPrimary: Color(0xFF000000),
          error: Color(0xFF8B0000),
          imageOverlay: Color(0xFF000000),
          onImageOverlay: Color(0xFFD0D0D0),
          textShadow: Color(0x8A000000),
          randomColors: [
            Color(0xFF4A4A4A),
            Color(0xFF5C5C5C),
            Color(0xFF383838),
            Color(0xFF6B6B6B),
            Color(0xFF2E2E2E),
            Color(0xFF525252),
            Color(0xFF3F3F3F),
            Color(0xFF606060),
            Color(0xFF484848),
            Color(0xFF555555),
            Color(0xFF333333),
            Color(0xFF8B0000),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF1A1A1A),
          secondary: Color(0xFF7F1D1D),
          tertiary: Color(0xFF6B7280),
          background: Color(0xFFFAFAFA),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFF0F0F0),
          onSurface: Color(0xFF0A0A0A),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFF7F1D1D),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF0A0A0A),
          textShadow: Color(0x8AFFFFFF),
          randomColors: [
            Color(0xFFD4D4D4),
            Color(0xFFC0C0C0),
            Color(0xFFE0E0E0),
            Color(0xFFB0B0B0),
            Color(0xFFCCCCCC),
            Color(0xFFD8D8D8),
            Color(0xFFC8C8C8),
            Color(0xFFBCBCBC),
            Color(0xFFD0D0D0),
            Color(0xFFC4C4C4),
            Color(0xFFE4E4E4),
            Color(0xFF7F1D1D),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Cinzel',
        bodyFamily: 'Crimson Text',
        displayWeight: FontWeight.w800,
        headlineWeight: FontWeight.w700,
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 0,
        cardBorderWidth: 2,
        inputRadius: 0,
        buttonRadius: 0,
      ),
    ),

    // ── Gojo ─────────────────────────────────────────────────────────
    // Red, Blue, Purple — swag, style, high tier, cool
    SenpwaiThemePreset.gojo => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFF7C3AED),
          secondary: Color(0xFFEF4444),
          tertiary: Color(0xFF3B82F6),
          background: Color(0xFF0C0A1A),
          surface: Color(0xFF13102A),
          surfaceVariant: Color(0xFF1E1A3A),
          onSurface: Color(0xFFE8E0FF),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFF43F5E),
          imageOverlay: Color(0xFF0C0A1A),
          onImageOverlay: Color(0xFFE8E0FF),
          textShadow: Color(0x8A000000),
          randomColors: [
            Color(0xFF8B5CF6),
            Color(0xFF6366F1),
            Color(0xFF3B82F6),
            Color(0xFFF43F5E),
            Color(0xFFD946EF),
            Color(0xFFA855F7),
            Color(0xFF2563EB),
            Color(0xFFEC4899),
            Color(0xFFC084FC),
            Color(0xFF818CF8),
            Color(0xFF60A5FA),
            Color(0xFFF472B6),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF6D28D9),
          secondary: Color(0xFFDC2626),
          tertiary: Color(0xFF2563EB),
          background: Color(0xFFF5F0FF),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFEDE5FF),
          onSurface: Color(0xFF1A1030),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFE11D48),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF1A1030),
          textShadow: Color(0x8AFFFFFF),
          randomColors: [
            Color(0xFF7C3AED),
            Color(0xFF4F46E5),
            Color(0xFF2563EB),
            Color(0xFFE11D48),
            Color(0xFFC026D3),
            Color(0xFF9333EA),
            Color(0xFF1D4ED8),
            Color(0xFFDB2777),
            Color(0xFFA855F7),
            Color(0xFF6366F1),
            Color(0xFF3B82F6),
            Color(0xFFEC4899),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Sora',
        bodyFamily: 'DM Sans',
        displayWeight: FontWeight.w700,
        headlineWeight: FontWeight.w600,
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 8,
        cardBorderWidth: 1,
        inputRadius: 8,
        buttonRadius: 8,
      ),
    ),

    // ── Deku ─────────────────────────────────────────────────────────
    // Green, White, Red — rounded, welcoming, comforting
    SenpwaiThemePreset.deku => const SenpwaiTheme(
      colors: SenpwaiColors(
        dark: SenpwaiColorSet(
          primary: Color(0xFF22C55E),
          secondary: Color(0xFFEF4444),
          tertiary: Color(0xFFFCD34D),
          background: Color(0xFF0A1A0F),
          surface: Color(0xFF111F16),
          surfaceVariant: Color(0xFF1A2F22),
          onSurface: Color(0xFFE5F5E0),
          onPrimary: Color(0xFF0A1A0F),
          error: Color(0xFFEF4444),
          imageOverlay: Color(0xFF0A1A0F),
          onImageOverlay: Color(0xFFE5F5E0),
          textShadow: Color(0x8A000000),
          randomColors: [
            Color(0xFF4ADE80),
            Color(0xFF22C55E),
            Color(0xFFEF4444),
            Color(0xFFFBBF24),
            Color(0xFF86EFAC),
            Color(0xFF14B8A6),
            Color(0xFFF87171),
            Color(0xFF6EE7B7),
            Color(0xFF34D399),
            Color(0xFFFCA5A5),
            Color(0xFFFDE68A),
            Color(0xFF10B981),
          ],
        ),
        light: SenpwaiColorSet(
          primary: Color(0xFF16A34A),
          secondary: Color(0xFFDC2626),
          tertiary: Color(0xFFD97706),
          background: Color(0xFFF0FFF4),
          surface: Color(0xFFFFFFFF),
          surfaceVariant: Color(0xFFE0F5E8),
          onSurface: Color(0xFF1A2E1C),
          onPrimary: Color(0xFFFFFFFF),
          error: Color(0xFFDC2626),
          imageOverlay: Color(0xFFFFFFFF),
          onImageOverlay: Color(0xFF1A2E1C),
          textShadow: Color(0x8AFFFFFF),
          randomColors: [
            Color(0xFF16A34A),
            Color(0xFF15803D),
            Color(0xFFDC2626),
            Color(0xFFD97706),
            Color(0xFF059669),
            Color(0xFF0D9488),
            Color(0xFFB91C1C),
            Color(0xFF047857),
            Color(0xFF0F766E),
            Color(0xFFEF4444),
            Color(0xFFF59E0B),
            Color(0xFF065F46),
          ],
        ),
      ),
      typography: SenpwaiTypography(
        displayFamily: 'Quicksand',
        bodyFamily: 'Nunito',
        displayWeight: FontWeight.w700,
        headlineWeight: FontWeight.w600,
      ),
      shape: SenpwaiShapeStyle(
        cardRadius: 14,
        cardBorderWidth: 0,
        inputRadius: 14,
        buttonRadius: 14,
      ),
    ),
  };
}
